### ISSUE TITLE
Issues with logging in

### ISSUE THREAD

**Issue by fredddyw** [aceiicle/Global-Cuisine-Quest#8]
Referring to my pull request,

Registration works perfectly, errors handled well, stores in database. Logging in logic works well as well, that is, it does not raise an error when an actual registered user is typed in (stored from db). However 1) it does not redirect successfully and instead stays on the page keeping the login form submission information in (the username not the password) and 2) doesn't seem like it keep a state that a user is actually logged in when submitted. This seems the case as when I click to Create a Challenge which has the @login_required decorator it redirects me to the login page where I type in my login details and then repeats issue 1. That's why I've commented out the decorator for now and everything works fine. I'll try and take a quick look at it if I can.

**Comment by windowl1ck3r** [comment]
Resolved in issue #4
